### ISSUE TITLE
Error on disk size

### ISSUE THREAD

**Issue by jrossthomson** [FluidNumerics/rcc-apps#3]
```
[1;31m==> googlecompute: Error creating instance: googleapi: Error 400: Invalid value for field 'resource.disks[0].initializeParams.diskSizeGb': '50'. Requested disk size cannot be smaller than the image size (100 GB), invalid[0m

```
200GB seems sufficient.

https://github.com/FluidNumerics/rcc-apps/blob/e4f28e808073d5b023318473cbc0639fe5477a90/gromacs/packer.json#L26

**Comment by fluidnumericsJoe** [comment]
@jrossthomson - Thanks for catching this and reporting. I've been meaning to take a sweep through the builds here to get disk_size pulled through as a build variable and have defaults set to values that will work.

**Comment by jrossthomson** [comment]
thanks, i may have more, struggling with a timeout, at this point. Let me add you to a chat...
