### ISSUE TITLE
Error with _ARCH variable

### ISSUE THREAD

**Issue by jrossthomson** [FluidNumerics/rcc-apps#5]
https://github.com/FluidNumerics/rcc-apps/blob/e4f28e808073d5b023318473cbc0639fe5477a90/gromacs/cloudbuild.yaml#L18

I get an error with _ARCH, but it is related to the env/spack.yaml issue.

**Comment by fluidnumericsJoe** [comment]
It looks like this reference didn't get updated to `${_TARGET_ARCH}` when I made some updates a couple months back. Pushing up a patch shortly, once the current build test finishes.

**Comment by fluidnumericsJoe** [comment]
@jrossthomson - you should be good to go with Gromacs builds
